### ISSUE TITLE
Cannot bootstrap metals snapshot: Malformed dependency

### ISSUE THREAD

**Issue by MasseGuillaume** [coursier/coursier#1099]
With coursier 1.1.0-M13-2

```bash
coursier bootstrap \
  --java-opt -XX:+UseG1GC \
  --java-opt -XX:+UseStringDeduplication  \
  --java-opt -Xss4m \
  --java-opt -Xms100m \
  --java-opt -Dmetals.client=sublime \
  org.scalameta:metals_2.12:0.4.4+120-d43ef03c-SNAPSHOT \
  -r sonatype:snapshots \
  -o ./metals-sublime-snapshot -f
```

```
Cannot parse dependencies:
  Malformed dependency:  
--java-opt: command not found
```

**Comment by alexarchambault** [comment]
It works for me… Does `coursier --help` confirms it's indeed `1.1.0-M13-2`?

**Comment by MasseGuillaume** [comment]
```
coursier --help
Coursier 1.1.0-M13-2
Usage: coursier [options] [command] [command-options]

Available commands: bootstrap, fetch, launch, resolve, spark-submit

Type  coursier command --help  for help on an individual command
```

**Comment by alexarchambault** [comment]
Works fine for me, both on OS X and Linux…

Could there be anything special with the default `sh` on your system? (`/usr/bin/env sh`, should correspond to `/bin/sh`)

https://github.com/coursier/coursier/pull/852 is able to remove some arguments, and pass them to `java` rather than coursier itself, but that's only for arguments starting with `-J`.

You're using the official launcher, right? (`https://git.io/coursier-cli`, redirects to stuff in github releases) I would expect your error when building the CLI from sources with `sbt cli/pack`, but not with the main launcher…

**Comment by MasseGuillaume** [comment]
`bootstrap` wraps a shell script? Is there a way to see the content of that script? I could see what's wrong on my system. I'm using nixos, it's a quite special system.

**Comment by alexarchambault** [comment]
It doesn't shell out, but the `coursier` launcher is itself the concatenation of a `sh` script and a JAR.

**Comment by MasseGuillaume** [comment]
I found the issue, whitespaces between java-opt triggers this bug.

**Comment by alexarchambault** [comment]
Closing this for now. Is the issue really on the coursier side?
