### ISSUE TITLE
a transitive non-optional dependency that is optional in its parent POM is missing

### ISSUE THREAD

**Issue by eed3si9n** [coursier/coursier#1336]
This was originally reported as https://github.com/sbt/sbt/issues/4968 by @anilkumarmyla 

## steps

Setup

```
$ cat build.sbt 
libraryDependencies ++= Seq(
  "net.javacrumbs.json-unit" % "json-unit" % "2.8.0"
)
$ cat project/sbt-dependency-graph.sbt 
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.10.0-RC1")
$ cat project/build.properties 
sbt.version=1.3.0-RC4
```

`sbt dependencyList test:dependencyList`

## problem

```
$ sbt dependencyList test:dependencyList
...
[info] default:optional_2.12:0.1.0-SNAPSHOT
[info] net.javacrumbs.json-unit:json-unit:2.8.0
[info] net.javacrumbs.json-unit:json-unit-core:2.8.0
[info] org.opentest4j:opentest4j:1.1.1
...
[info] default:optional_2.12:0.1.0-SNAPSHOT
[info] net.javacrumbs.json-unit:json-unit:2.8.0
[info] net.javacrumbs.json-unit:json-unit-core:2.8.0
[info] org.opentest4j:opentest4j:1.1.1
```

This is missing `org.hamcrest:hamcrest-core:1.3`.

## expectations

It includes `org.hamcrest:hamcrest-core:1.3` as it did in sbt 1.2.8.

## notes

https://repo1.maven.org/maven2/net/javacrumbs/json-unit/json-unit-parent/2.8.0/json-unit-parent-2.8.0.pom

```xml
<dependency>
  <groupId>org.hamcrest</groupId>
  <artifactId>hamcrest-core</artifactId>
  <version>1.3</version>
  <optional>true</optional>
</dependency>
```

https://repo1.maven.org/maven2/net/javacrumbs/json-unit/json-unit-core/2.8.0/json-unit-core-2.8.0.pom

```xml
<dependency>
  <groupId>org.hamcrest</groupId>
  <artifactId>hamcrest-core</artifactId>
</dependency>
```

**Comment by anilkumarmyla** [comment]
We use json-unit widely in our unit tests and having to add org.hamcrest in each project raises a lot of questions.

**Comment by alexarchambault** [comment]
This looks like a "won't fix".

Per the [Maven documentation](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Management), the key to match a dependency with a dependency management entry consists in `{groupId, artifactId, type, classifier}`. `optional` isn't part of the key, so it ends up being pulled from dependency management, like `version`. That how coursier currently behaves, and that's what we're seeing here with `org.hamcrest:hamcrest-core`.

It seems this is related to [a Maven bug](https://issues.apache.org/jira/browse/MNG-5227), mentioned in [this StackOverflow question](https://stackoverflow.com/questions/23611254/is-the-tag-optional-valid-in-dependencymanagement-element). So in the future, Maven should behave the same as coursier, and consider `org.hamcrest:hamcrest-core` optional.

So the problem ought to be fixed upstream in the json-unit-parent POM, IMO. The optional tag on hamcrest-core should be removed from there. I'm not sure I want to "fix" that in coursier, given that this is considered a bug in Maven, hopefully fixed in the future.

**Comment by anilkumarmyla** [comment]
thanks @alexarchambault for looking into this. filed issue at https://github.com/lukas-krecan/JsonUnit/issues/193

**Comment by anilkumarmyla** [comment]
Given https://github.com/lukas-krecan/JsonUnit/issues/193 is fixed/closed, should we keep this issue open? I'm good with closing this issue

**Comment by alexarchambault** [comment]
Closing then, thanks @anilkumarmyla! (and @eed3si9n for reporting the issue and the initial investigation)
