### ISSUE TITLE
ignores .credentials file (from sbt 1.3.3)

### ISSUE THREAD

**Issue by TimPigden** [coursier/coursier#1421]
Using sbt 1.3.3 and coursier with a credentials file it does not find a https file-based pom file - giving unauthenticated message and using ldap basic authentication

See https://github.com/sbt/sbt/issues/5200 for more details

See https://gitlab.com/wayne-optrak/sbt-bug-demo for very simple example - just grab the repo and run sbt update

Apologies if this amounts to a duplicate but it's not clear from other reports.

**Comment by Voltir** [comment]
I think we are running into this problem as well.

**Comment by cchepelov** [comment]
Had the same problem in sbt 1.4.6 (which uses Coursier 2.0.8 via sbt-coursier 2.0.5)

I could trace the issue to the fact that Nexus now adds an additional `, charset="UTF-8"` to its `www-authenticate` HTTP 401 reply.

https://github.com/sbt/sbt/issues/5200#issuecomment-760199502

The solution I intend to apply is to rewrite the "realm picker" by first parsing every item out of the www-authenticate header and then taking the realm, rather than a simple regex.
