### ISSUE TITLE
cs bootstrap / cs install launcher script not working with private `-r` repositories

### ISSUE THREAD

**Issue by chadselph** [coursier/coursier#1774]
I ran into this issue when test [my wrapper](https://github.com/chadselph/coursier-private-repo-boostrap) which loads .m2 credentials for private maven repositories.

To reproduce:

```console
$ cs launch --credentials ... -r https://private/pro com.company:app:0.1.0 -M com.company.Main
```

this works, downloads jars, command runs but when running bootstrap:

```console
$ cs bootstrap --credentials ... -r https://private/pro com.company:app:0.1.0 -M com.company.Main -o app
```
everything downloads and resolves correctly but when running
``` console
$ ./app
Error while downloading https://private/repo/...app-0.1.0-SNAPSHOT.jar: 
Server returned HTTP response code: 401 for URL: https://... ignoring it
```

it suddenly forgets it has already downloaded the dependencies (and doesn't try to use credentials even if they're written to the credentials.properties file).

Reproduced in a docker container (openjdk11-jre-slim) with `cs --version` `2.0.0-RC6-21`.

**Comment by alexarchambault** [comment]
I confirm credentials are not persisted in bootstraps. Bootstraps are only for repositories with no authentication for now.

Ideally, I'd like [global credentials](https://get-coursier.io/docs/other-credentials.html#property-file) to be used from bootstraps too, but they aren't yet…

**Comment by chadselph** [comment]
yeah bootstraps should definitely not contain the credentials, but it's already downloaded the jars. It's just looking for them in the wrong place: `.cache/coursier/v1/https/user%40server/` vs `.cache/coursier/v1/https/user%40server/`. So, this bootstrap will not be sharable, but it should still run, right? If not, why did the bootstrap command even download them?

The use case I have in actually for the install command. I have an internal URL app channel which points to the internal maven repo.

**Comment by chadselph** [comment]
I'll also mention I found two workarounds.
For cs bootstrap using `--manifest-jar` works
For using app channels, using a standalone or hybrid launcher works.

That being said including the username in the file cache path still seems wrong to me, could there at least be an option to turn it off?

**Comment by greg-a-atkinson** [comment]
> I confirm credentials are not persisted in bootstraps. Bootstraps are only for repositories with no authentication for now.
> 
> Ideally, I'd like [global credentials](https://get-coursier.io/docs/other-credentials.html#property-file) to be used from bootstraps too, but they aren't yet…

Hi @alexarchambault 

I have a similar issue. Within my organisation we use a private authenticated Artifactory repository to serve all internal and external repositories. Ideally we would like to retrieve artifacts through this repository and not via a proxy. (A proxy requires domain credentials, while Artifactory only requires a user specific Artifactry API key, which more secure for adding to configuration files/properties/variables than domain credentials.)

When I configure the following `mirror.properties`:

```
central.from=https://repo1.maven.org/maven2
central.to=https://private.artifactory.com/artifactory/mavencentral
jcenter.from=https://jcenter.bintray.com
jcenter.to=https://private.artifactory.com/artifactory/jcenter
typesafe.from=https://repo.typesafe.com/typesafe/ivy-releases
typesafe.to=https://private.artifactory.com/artifactory/typesafe-ivy-releases
```

Most artifact retrievals succeed, but artifacts retrieved by the bootstrap launcher fail. For example, the Scala Metals plugin for VSCode fails to download various artifacts due to `401 Unauthorized` errors when the bootstrap launcher does not use the configured [global credentials](https://get-coursier.io/docs/other-credentials.html#property-file):

```
Java home: C:\Users\zkjakch\working\tools\jdk1.8.0_261-x64
Metals version: 0.9.10
Error while downloading https://private.artifactory.com/artifactory/virtual-java/com/chuusai/shapeless_2.12/2.3.3/shapeless_2.12-2.3.3.jar: Server returned HTTP response code: 401 for URL: https://private.artifactory.com/artifactory/virtual-java/com/chuusai/shapeless_2.12/2.3.3/shapeless_2.12-2.3.3.jar, ignoring it
Error while downloading https://private.artifactory.com/artifactory/virtual-java/com/github/alexarchambault/case-app-annotations_2.12/2.0.0-M9/case-app-annotations_2.12-2.0.0-M9.jar: Server returned HTTP response code: 401 for URL: https://private.artifactory.com/artifactory/virtual-java/com/github/alexarchambault/case-app-annotations_2.12/2.0.0-M9/case-app-annotations_2.12-2.0.0-M9.jar, ignoring it
Error while downloading https://private.artifactory.com/artifactory/virtual-scala/com.lightbend/emoji_2.12/1.2.1/jars/emoji_2.12.jar: Server returned HTTP response code: 401 for URL: https://private.artifactory.com/artifactory/virtual-scala/com.lightbend/emoji_2.12/1.2.1/jars/emoji_2.12.jar, ignoring it
Error while downloading https://private.artifactory.com/artifactory/virtual-java/com/github/alexarchambault/argonaut-shapeless_6.2_2.12/1.2.0-M11/argonaut-shapeless_6.2_2.12-1.2.0-M11.jar: Server returned HTTP response code: 401 for URL: https://private.artifactory.com/artifactory/virtual-java/com/github/alexarchambault/argonaut-shapeless_6.2_2.12/1.2.0-M11/argonaut-shapeless_6.2_2.12-1.2.0-M11.jar, ignoring it
```

The bootstrap launcher is a Java-only module, which makes sense as it will only have use of the core Java libraries before any dependencies are downloaded, but as a consequence it does not have access to the current Scala-based `Credentials` functionality. Your suggestion that "ideally [you'd] like [global credentials](https://get-coursier.io/docs/other-credentials.html#property-file) to be used from bootstraps" could be implemented in a number of ways, each with different pros and cons:

1. The `bootstrap-launcher` module is enhanced with just enough Java-based functionality to utilize the [global credentials](https://get-coursier.io/docs/other-credentials.html#property-file) without any changes to the existing, out-of-scope Scala-based credentials functionality. Pros: No change to the the Scala `Credentials` API or implementation. Cons: Some duplication.
2. A new or exisitng Java-only module, like `paths`, could be enhanced with the complete credentials functionality, the Scala API updated to delegate to the Java implementation and the `boostrap-launcher` updated to utilize the common credentials functionality. Pros: A single credentials implementation. Cons: Change, compatibility and larger initiative.
3. Some else?

Do you have a preferred implementation in mind?

The following pull request is along the lines of possible implementation (1) above: https://github.com/coursier/coursier/pull/1990

What do you think?

Happy to discuss.

Thanks

Kind regards,
Greg

**Comment by chadselph** [comment]
Looks like this is working now! thanks @greg-a-atkinson
