### ISSUE TITLE
`cs update cs` doesnt work

### ISSUE THREAD

**Issue by xhudik** [coursier/coursier#2014]
Hi there,

It seems there is a problem with `cs update`. I have cs version `2.0.8` and could not update to the newest `2.0.15`:
```bash
cs --version
2.0.8

cs update cs
https://repo1.maven.org/maven2/io/get-coursier/coursier-cli_2.12/maven-metadata.xml
  No new update since 2021-03-21 14:05:47

cs --version
2.0.8


cs complete io.get-coursier:coursier-cli_2.12: | grep 2.0.1
2.0.1
2.0.10
2.0.11
2.0.12
2.0.13
2.0.14
2.0.15
```
Any idea what is wrong? Am I missing something?

**Comment by alexarchambault** [comment]
@xhudik Are you on Windows? The following should work then:
```text
$ cs update coursier
$ coursier --help # should print the latest version
$ coursier update cs
$ cs --help # should print the latest version
```

It may fail to update because of the former `cs update cs` runs though. In that case, remove `cs` and any `.cs*` file manually, and run `coursier install cs`. If the coursier update fails, remove `coursier` and any `.coursier*` files, and run `cs install coursier`.

This needs to be mentioned in the documentation... (and worked around too...)

**Comment by xhudik** [comment]
nope, I'm on Linux Ubuntu 20.04. Ok, I'll try - thank for the support!
