### ISSUE TITLE
Incorrect coordinate strings in JSON report for Bouncy Castle dependencies

### ISSUE THREAD

**Issue by alonsodomin** [coursier/coursier#2315]
Initially reported in Pants at pantsbuild/pants#13986.

Coursier is showing swapped values of the `version` and `packaging` parts of an artifact coordinates for the case of the Bouncy Castle JARs.

Using Coursier: 2.1.0
Run the following command:

```bash
cs fetch --json-output-file=deps.json "org.bouncycastle:bcutil-jdk15on:1.70"
```

Inspecting the contents of the generated report at `deps.json`, it can be seen how the coordinates for the dependencies are showing in incorrect form:

```json
{
  "conflict_resolution": {},
  "dependencies": [
    {
      "coord": "org.bouncycastle:bcprov-jdk15on:jar:1.70",
      "file": "/Users/alonsodomin/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/bouncycastle/bcprov-jdk15on/1.70/bcprov-jdk15on-1.70.jar",
      "directDependencies": [],
      "dependencies": []
    },
    {
      "coord": "org.bouncycastle:bcutil-jdk15on:1.70",
      "file": "/Users/alonsodomin/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/bouncycastle/bcutil-jdk15on/1.70/bcutil-jdk15on-1.70.jar",
      "directDependencies": [
        "org.bouncycastle:bcprov-jdk15on:jar:1.70"
      ],
      "dependencies": [
        "org.bouncycastle:bcprov-jdk15on:jar:1.70"
      ]
    }
  ],
  "version": "0.1.0"
}
```

The dependencies are showing coordinates `org.bouncycastle:bcprov-jdk15on:jar:1.70` which follows format `[organisation]:[artifact]:[packaging]:[version]`, the expectation is to use `[organisation]:[artifact]:[version]:[packaging]`.

It may be that the expectation is wrong to start with, but it's assumed to be like that due to the fact that the fromat used in the command line is `[organisation]:[artifact]:[version]`.

**Comment by stuhood** [comment]
> The dependencies are showing coordinates `org.bouncycastle:bcprov-jdk15on:jar:1.70` which follows format `[organisation]:[artifact]:[packaging]:[version]`, the expectation is to use `[organisation]:[artifact]:[version]:[packaging]`.
> 
> It may be that the expectation is wrong to start with, but it's assumed to be like that due to the fact that the fromat used in the command line is `[organisation]:[artifact]:[version]`.

It looks like this layout is due to the use of `mavenPrefix` here: https://github.com/coursier/coursier/blob/b5d5429a909426f4465a9599d25c678189a54549/modules/cli/src/main/scala/coursier/cli/util/JsonReport.scala#L128, ([defined here](https://github.com/coursier/coursier/blob/b5d5429a909426f4465a9599d25c678189a54549/modules/core/shared/src/main/scala/coursier/core/Dependency.scala#L24-L28)).

This is the only place that `mavenPrefix` is used, so it does seem likely that this is inconsistent with how coordinates are rendered in general. Additionally, I don't see any other places where the `packaging` is rendered (for example, nowhere in `modules/core/shared/src/main/scala/coursier/util/Print.scala`, as far as I can tell).

The examples on the site are all rendering the `classifier` alone, and they render it as `[organisation]:[artifact]:[version]:[classifier]`. So at the very least, if `def mavenPrefix` were used to render a `classifier` (it doesn't in @alonsodomin's example), it would be rendered in an inconsistent location).

**Comment by alonsodomin** [comment]
Looks

**Comment by alonsodomin** [comment]
Looks like if the artifact had a classifier as well, then the version coordinante would be even more displaced.

By looking at pantsbuild/pants#13990, it seems this would happen for reconciled transitive dependencies that have a `<type>jar</type>` element in their poms.

I'm not very familiar with coursier's code, maybe this is _as easy_ as replacing the usage of `mavenPrefix` by a method thst takes the `dep` object with the reconciled version and renders the coordinates accordingly. That should support the usage of the classifier as well.

**Comment by alonsodomin** [comment]
After checking this behaviour against the reference implementation in Eclipse Aether, turns out my expectation was (unsurprisingly) wrong.

The Maven coords are indeed `[organization]:[artifact]:[[extension]:[classifier]]:[version]`

So version number would always be last. My bad, I jumped the gun with this one here.
