### ISSUE TITLE
Scala 2.12.16 version of sbt-coursier

### ISSUE THREAD

**Issue by eed3si9n** [coursier/coursier#2573]
I am probably going to publish sbt 1.8.0 RC or milestone so people can start using scala-xml, but could we also maintain a branch with Scala 2.12.17 as well for 1.7.x series until 1.8.x matures?

Thanks!

**Comment by alexarchambault** [comment]
I've been discussing that a bit with @adpi2 on other channels. There should be two ways of achieving this IMO:
- either branching, or
- duplicating some modules in the main build, so that they stay on former scala / scala-xml versions and are published with a suffix appended to their version.

I think the second option should be easier to maintain, and shouldn't be too costly to setup either.

**Comment by adpi2** [comment]
I am trying solution 2: deduplication of modules in the main build.

As a version suffix I can use `sbt17` or `scalaxml1`. Do you have any better idea?

**Comment by alexarchambault** [comment]
@adpi2  `scalaxml1` maybe.

**Comment by adpi2** [comment]
Since sbt 1.8.0 was released yesterday, I will not pursue on this. Let me know if you think we still need the Scala 2.12.16 version of Coursier.
