### ISSUE TITLE
Missing 2.1.1 binaries, linked from Scala website

### ISSUE THREAD

**Issue by SethTisue** [coursier/coursier#2739]
reported on Scala Discord just now:

> hello, I'm trying to install Scala, but the link on the official website appears to be dead? (for Windows)
> this link:
> https://github.com/coursier/coursier/releases/download/v2.1.1/cs-x86_64-pc-win32.zip
> found on this page:
> https://docs.scala-lang.org/getting-started/index.html

**Comment by alexarchambault** [comment]
That link works for me, not sure why it's a problem for that Discord user.

**Comment by SethTisue** [comment]
it works now — didn't work at the time I opened the ticket

**Comment by rayrobdod** [comment]
The link on the website is actually to `latest`, which at the time redirected to `v2.1.1`.

The discord user happened to try using the `latest` link between when the `v2.1.1` tag was created and when the `v2.1.1` github actions finished the "Upload launchers to GitHub release assets" step. Since the action has finished by now, the link does work. However, I imagine the `latest` link would have the same hourish of downtime immediately after any future coursier releases.

If there were a way to mark a release as `latest` after the actions have finished instead of at the start the actions, that should prevent the latest binary links from having any downtime, but I don't know if there is a way to do that.

**Comment by alexarchambault** [comment]
> If there were a way to mark a release as latest after the actions have finished instead of at the start the actions, that should prevent the latest binary links from having any downtime, but I don't know if there is a way to do that.

That’s what we should do, yes…
