### ISSUE TITLE
Coursier ignores overridden properties in child POM

### ISSUE THREAD

**Issue by ppkarwasz** [coursier/coursier#2906]
In the Apache Log4j project we support multiple versions of the same library (in different Maven modules).

In order to do that, in the **parent** POM we specify the version of the library via a Maven property:

```xml
<properties>
  <slf4j.version>2.0.9</slf4j.version>
</properties>
<dependencyManagement>
  <dependencies>
      <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-api</artifactId>
        <version>${slf4j.version}</version>
      </dependency>
  </dependencies>
</dependencyManagement>
```

and we overwrite the property value in the child POM:

```xml
<properties>
  <slf4j.version>1.7.25</slf4j.version>
</properties>
```

This works very well with Maven, since the _"inheritance assembly"_ phase precedes the _"model interpolation"_ phase (cf. [Maven Model Builder](https://maven.apache.org/ref/3.9.6/maven-model-builder/)).

However, as reported by one of our users (cf. apache/logging-log4j2#2065) this doesn't work with Coursier: in the above example Maven with choose version `1.7.25` while Coursier will choose version `2.0.9`.

**Comment by gatisnolv** [comment]
I think you meant that you specify `<slf4j.version>2.0.9</slf4j.version>` and not `<slf4j.api>2.0.9</slf4j.api>` in the Parent POM, so in your redacted example:
```
<properties>
  <slf4j.version>2.0.9</slf4j.version>
</properties>
<dependencyManagement>
...
```
Links to the referenced pom files for easy access:
- [Parent pom](https://github.com/apache/logging-log4j2/blob/2.x/log4j-parent/pom.xml)
- [Child pom](https://github.com/apache/logging-log4j2/blob/2.x/log4j-slf4j-impl/pom.xml)


I created a minimal example to reproduce this and the steps are almost the same as what I described for this other [issue](https://github.com/coursier/coursier/issues/2790) I reported earlier, but I include them below as well.
Similarly to that other issue, I want to point out that since this is the behavior irrespective of whether the parent or child project has a higher version, it is clear that this is NOT an example of the difference in version handling between [Coursier](https://get-coursier.io/docs/other-version-handling) and [Maven](https://github.com/coursier/coursier/issues/418#issuecomment-487800709) (latest-wins vs nearest-wins), but a separate issue.

Setup: Maven 3.9.0, Coursier 2.1.8
Note: I couldn't figure out how to directly run `cs resolve` against the local Maven repository, so to serve it on localhost, from `~/.m2/repository` run something like `npx http-server` (or whatever web server you prefer), making it available on http://localhost:8080/

Minimal example: https://github.com/gatisnolv/coursier-issue-2906

Reproduction:
Run `mvn install` in each of `./parent`, `./parent/child` directories to install the projects to the Maven local repository.
Observe the difference in result when running inside of the `./parent/child` directory `mvn dependency:tree` against the output of `cs resolve -q --cache "./" --repository "http://localhost:8080/" org.fake:child:1.0-SNAPSHOT; rm -rf http*`

Note: in the `cs resolve` command I specify to use as cache the current directory, and do an `rm -rf http*` after it's done to get updated results in the next run if I change something in the poms (and reinstall them again with `mvn install`).

**Comment by ppkarwasz** [comment]
@gatisnolv, thanks, I corrected my message.

For the examples, it is better to point at the published versions, since those in Git can change:

- [child POM](https://repo.maven.apache.org/maven2/org/apache/logging/log4j/log4j-slf4j-impl/2.22.0/log4j-slf4j-impl-2.22.0.pom),
- [parent POM](https://repo.maven.apache.org/maven2/org/apache/logging/log4j/log4j/2.22.0/log4j-2.22.0.pom)
