### ISSUE TITLE
coursier doesn't seem to handle the ejb packaging properly

### ISSUE THREAD

**Issue by thescouser89** [coursier/coursier#3040]
# Issue
While using sbt >= 1.9.4, which uses coursier 2.1.6, it seems that it doesn't handle the ejb packaging properly. An example is https://repo1.maven.org/maven2/org/jboss/da/reports-model/2.1.0/reports-model-2.1.0.pom , which has packaging ejb but the artifact itself is a jar.

I hit the issue on sbt and reported the bug [here](https://github.com/sbt/sbt/issues/7612). There is also a reproducer posted on that issue.

@eed3si9n has kindly pointed out that https://github.com/coursier/coursier/pull/2718 might have introduced the issue.

**Comment by eed3si9n** [comment]
sbt 1.9.4 bumped Cousier from 2.1.2 to 2.1.6. My guess that the underlying non-support has been there from the beginning, but somehow the recent change has shook the system to expose it. So I think of it more as it likely triggering this, rather than causing it.

In any case, the fix should be to register ejb type as a jar extension artifact. I think there are others like `maven-plugin` that act in a similar way already being supported.

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/coursier/coursier/pull/3041
