### ISSUE TITLE
Whitespace in version not handled

### ISSUE THREAD

**Issue by flicken** [coursier/coursier#408]
Whitespace in a version of a transitive dependency is not handled correctly.  For example, the following dependency:

`libraryDependencies += "org.jboss.resteasy" % "resteasy-jaxrs" % "3.0.19.Final"`

Results in the following error

> 
> [info] Resolved coursier-bug-whitespace dependenciesmmons-parent/28/commons-parent-28.pom
> [trace] Stack trace suppressed: run last *:coursierResolution for the full output.
> [error] (*:coursierResolution) coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
> [error]   org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.0_spec:1.0.0.Final
> [error]         :
> [error]     not found:
> [error]       /Users/broberts/.ivy2/local/org.jboss.spec.javax.ws.rs/jboss-jaxrs-api_2.0_spec/1.0.0.Final
> [error]         /ivys/ivy.xml
> [error]       https://repo1.maven.org/maven2/org/jboss/spec/javax/ws/rs/jboss-jaxrs-api_2.0_spec/1.0.0.Final%0A%20%20%20%20%20%20%20%20/jboss-jaxrs-api_2.0_spec-1.0.0.Final%0A%20%20%20%20%20%20%20%20.pom
> [error] Total time: 3 s, completed Dec 8, 2016 8:42:23 AM

Minimal project showing bug: https://github.com/flicken/coursier-bug-whitespace

**Comment by alexarchambault** [comment]
Thanks for the repro! The problem can also be reproduced with the CLI tool via
```
$ coursier fetch org.jboss.resteasy:resteasy-jaxrs:3.0.19.Final

Error:
  org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.0_spec:1.0.0.Final
        :
    not found: ~/.ivy2/local/org.jboss.spec.javax.ws.rs/jboss-jaxrs-api_2.0_spec/1.0.0.Final
        /ivys/ivy.xml
    not found: https://repo1.maven.org/maven2/org/jboss/spec/javax/ws/rs/jboss-jaxrs-api_2.0_spec/1.0.0.Final%0A%20%20%20%20%20%20%20%20/jboss-jaxrs-api_2.0_spec-1.0.0.Final%0A%20%20%20%20%20%20%20%20.pom
```

Whitespace trimming in Maven is discussed [here](https://stackoverflow.com/questions/7389995/how-do-i-preserve-whitespace-in-a-maven-plugin-configuration) or [there](https://issues.apache.org/jira/browse/MNG-5380).

I guess versions can be trimmed just before being parsed. Some trimming already occurs since @eboto 's fix in https://github.com/alexarchambault/coursier/pull/354.
