### ISSUE TITLE
Q: is it safe to launch multiple instances of coursier?

### ISSUE THREAD

**Issue by wisechengyi** [coursier/coursier#411]
Assume they share the same cache directory. Would one stump another in terms of saving the same artifact or checking the cache that is still being saved?

**Comment by alexarchambault** [comment]
It should be fine in terms of (non) file corruption. The only problem you may run into is if two concurrent resolutions fetch a given file at the same time: one will lock it, which makes concurrent attempts fail (with an error message saying `locked`). Simply retrying the attempts that fail because of `locked` errors addresses the problem (once the file is fully downloaded), but this has to be done manually for now.

**Comment by alexarchambault** [comment]
`1.0.0-RC4` should now be fine with multiple coursier downloading the same file (one will actually download the file, the other will report its progress, ready to step up if ever the actual download is interrupted.)
