### ISSUE TITLE
Missing ivy credentials file makes coursier go boom

### ISSUE THREAD

**Issue by pjan** [coursier/coursier#438]
How to reproduce:

Add the following to your sbt build, in combination with the resolution of dependencies that depend on this, but make sure the file is not there:

`Credentials(Path.userHome / ".ivy2" / ".credentials")`

as opposed to the regular sbt dependency resolution, coursier crashes.

**Comment by Jentsch** [comment]
For everyone who is wondering what exception is thrown that makes “coursier goes boom“ (Like the phrase :-) ): It's a `FileNotFoundException`

It's thrown in [Credentials.scala Line 26](https://github.com/coursier/coursier/blob/a6b9c845c280bfc423b3f646bcaf4be7a4a6f07e/sbt-coursier/src/main/scala-2.10/coursier/Credentials.scala#L26). A similar thing happens if the username or password isn't defined. [Line 36, same file](https://github.com/coursier/coursier/blob/a6b9c845c280bfc423b3f646bcaf4be7a4a6f07e/sbt-coursier/src/main/scala-2.10/coursier/Credentials.scala#L37).

From a user perspective I think it would be the best if instead of crashing the plugin should just drop a warning and ignoring the file. (Something along the lines “Hey stupid user, a credentials file is missing. If the dependency resolution couldn't find all your little libraries this is properly the reason.”) But I think this requires a change of the signature of [Credentials.apply(File)](https://github.com/coursier/coursier/blob/a6b9c845c280bfc423b3f646bcaf4be7a4a6f07e/sbt-coursier/src/main/scala-2.10/coursier/Credentials.scala#L54) to File -> Option[Credentials] and this will brake existing code :-/

An other option that I see is dropping readable error message and don't show a stack trace with [MessageOnlyException of sbt](http://www.scala-sbt.org/0.13.11/api/#sbt.MessageOnlyException).

@alexarchambault what would you prefer?

**Comment by alexarchambault** [comment]
Ran into a similar exception thrown around [here](https://github.com/coursier/coursier/blob/6c1b8ea7a4235a446d554e2b7201962ea872cccc/sbt-coursier/src/main/scala-2.10/coursier/Tasks.scala#L461)... I guess here too some guards could be added.

@Jentsch It's fine breaking (rather internal) stuff in the plugin module. The signature of `Credentials.apply` could be changed.

**Comment by aij** [comment]
Would it be possible to warn only once (when the absence of the file is first observed), rather than filling the screen with warnings, as it continues to not exist.
