### ISSUE TITLE
Dependency classifiers are ignored

### ISSUE THREAD

**Issue by omervk** [coursier/coursier#444]
The dependency `"org.apache.spark" %% "spark-sql" % "2.0.2" classifier "tests"` resolves to the same dependency as `"org.apache.spark" %% "spark-sql" % "2.0.2"`.

This is a regression (worked in M15, doesn't in M15-2).

**Comment by alexarchambault** [comment]
Adding
```scala
classpathTypes += "test-jar"
```
fixes that for me.

I don't know if this is actually a bug. Asking for type `test-jar` is something that seems to be done from Maven ([here](https://maven.apache.org/guides/mini/guide-attached-tests.html) or [there](https://maven.apache.org/plugins/maven-jar-plugin/test-jar-mojo.html)). I don't know if this is something Maven requires all the time for these.

This behavior appeared in coursier in `1.0.0-M15-2` after the Maven classifiers and artifact types handling was reworked a bit, hopefully to make it more robust. JARs with classifier `tests` and extension `jar` are now assumed to have type `test-jar` rather than `jar`. `test-jar` type has thus to be added to the classpath to add these JARs. IIRC, I saw the `test-jar` around [this method](https://github.com/sbt/sbt/blob/0.13/sbt-maven-resolver/src/main/scala/sbt/mavenint/MavenRepositoryResolver.scala#L498-L509) in the sources of sbt.

**Comment by omervk** [comment]
Thanks, this worked for me!

**Comment by trentontrees** [comment]
I've created a PR with a test around this: #510
From my testing, this is not resolved in 1.0.0-RC1
