### ISSUE TITLE
Customize `bootstrap.jarDir` for bootstrap

### ISSUE THREAD

**Issue by markus1189** [coursier/coursier#530]
First of all: coursier is great! Thanks for all the work. Now to my issue:

I want to fetch some dependencies using `coursier` for which I am building a custom fetcher for `nix`.  Unfortunately, the following script:

```
coursier bootstrap --standalone $groupId:$artifactId:$version -o $out/$name --main $main
```

fails under `nix` with: 

```
Warning: cannot create /var/empty/.coursier/bootstrap/1.0.0-RC1, continuing anyway.
Error while downloading https://oss.sonatype.org/content/repositories/releases/io/get-coursier/coursier-cli_2.11/1.0.0-RC1/coursier-cli_2.11-1.0.0-RC1-standalone.jar: /var/empty/.coursier/bootstrap/1.0.0-RC1/coursier-cli_2.11-1.0.0-RC1-standalone.jar--443301202 (No such file or directory), ignoring it
builder for ‘<snip>’ failed with exit code 255
```

It seems as if the `bootstrap.jarDir` property points to `$HOME`, which is set to an immutable empty directory for builds running with nixos. 

**My question:** is there any way to customize this setting: https://github.com/coursier/coursier/blob/e430b6051c2e04793e891e9949f6ff67c841c844/bootstrap/src/main/java/coursier/Bootstrap.java#L359

**Comment by olafurpg** [comment]
Duplicate of https://github.com/coursier/coursier/issues/511 ?

**Comment by alexarchambault** [comment]
@markus1189 If that's possible for you, you could rely straightaway on the JAR that the launcher downloads (and puts under `~/.coursier/bootstrap`). Currently, it's at [this address](http://repo1.maven.org/maven2/io/get-coursier/coursier-cli_2.11/1.0.0-RC2/coursier-cli_2.11-1.0.0-RC2-standalone.jar). You can launch this JAR via a `java -jar coursier-cli_2.11-1.0.0-RC2-standalone.jar coursier-args...` instead of `coursier coursier-args...`.

**Comment by alexarchambault** [comment]
coursier should then only rely on its cache, by default under `~/.coursier/cache/v1`, but this can be changed via `COURSIER_CACHE` in the environment.

**Comment by markus1189** [comment]
@alexarchambault that solves it for my case, thanks!
