### ISSUE TITLE
Very slow dependency resolving

### ISSUE THREAD

**Issue by yurique** [coursier/coursier#591]
I'm using `RC5` version of `sbt-coursier` (`addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-RC5")
`).

When I issue `compile` in sbt for the first time after loading it it takes a really long time to resolve dependencies. It looks like this:

```
[info] Updating someModule (sbt classifiers)
http://repo.typesafe.com/typesafe/releases/org/flywaydb/flyway-sbt_2.10_0.13/4.2.0/flyway-sbt-4.2.0.pom.sha1
    0.0% [          ] 0 B (0 B / s)
```

I just started `complile` and it took it several minutes to do all that and actually start compiling (no artifacts were downloaded, just checking metadata).

I restarted sbt and `compile`d again - it's stuck at

```
https://repo.typesafe.com/typesafe/ivy-releases/org.flywaydb/flyway-sbt/scala_2.10/sbt_0.13/4.2.0/ivys/ivy.xml.sha1
    0.0% [          ] 0 B (0 B / s)
```

for a couple of minutes now.

This wasn't happening before `RC3` (switched to it from `M15`).

**Comment by alexarchambault** [comment]
The `https://repo.typesafe.com/...` repositories are usually quite slow in my experience too. Although once the corresponding file is in cache (from this repo or another), the `https://repo.typesafe.com/...` repo shouldn't be checked for it... (but new files are downloaded since `1.0.0-RC1`)

sbt usually gives these slow repositories a high priority, but  https://github.com/coursier/coursier/commit/a91b955a9ff7765740b35eae2c286ad55d2b58d4 should now lower it from sbt-coursier. It will be included in `1.0.0-RC6`, about to be released.

**Comment by yurique** [comment]
Cool! I updated to RC6 and it does seem to be faster now :+1: 

Out of curiosity - why are those URLs slow? (like http://repo.typesafe.com/typesafe/releases/org/flywaydb/flyway-sbt_2.10_0.13/4.2.0/flyway-sbt-4.2.0.pom.sha1). `curl`ing them works pretty fast, lke 300ms for me and definitely not minutes.

**Comment by alexarchambault** [comment]
The `repo.typesafe.com` just feels slow compared to Central, in my experience. Plus it doesn't seem to accept several connections in parallel, effectively answering only one of them at once.

(Closing the issue...)
