### ISSUE TITLE
Conflict(s) in dependency resolution

### ISSUE THREAD

**Issue by cheleb** [coursier/coursier#779]
I don't know who is guilty :), but the project build without coursier.

https://github.com/spotify/scio

[error] coursier.ResolutionException: Conflict(s) in dependency resolution:
[error]   io.grpc:grpc-core:1.2.0:default(compile)
[error] io.grpc:grpc-core:1.5.0:default(compile)
[error] io.grpc:grpc-core:1.6.1:default(compile)
[error] (*:coursierResolutions) coursier.ResolutionException: Conflict(s) in dependency resolution:
[error]   io.grpc:grpc-core:1.2.0:default(compile)
[error] io.grpc:grpc-core:1.5.0:default(compile)
[error] io.grpc:grpc-core:1.6.1:default(compile)
[error] Total time: 4 s, completed Feb 14, 2018, 3:38:19 PM

**Comment by wisechengyi** [comment]
You may try forcing the version to work around it. https://github.com/coursier/coursier/issues/701#issue-277658844

**Comment by alexarchambault** [comment]
I'd like to push a document with some explanations about that error… The error is legit, and I'd like to check why maven or sbt are fine with it (it might be because they just don't try to fix version conflicts, but I'd like to check).

Also, the output of coursier could be clearer here. It should print the actual conflict, like
```
io.grpc:grpc-core:1.2.0:default(compile)
io.grpc:grpc-core:[1.5.0,1.6.0[:default(compile)
io.grpc:grpc-core:[1.6.0,1.7.0[:default(compile)
```
(the actual error was along those lines iirc). It was a one-line change.

**Comment by alexarchambault** [comment]
(low hanging fruit label for the clearer output ^)

**Comment by joan38** [comment]
What's left to do on this one? I can see the clearer output is implemented.

**Comment by alexarchambault** [comment]
Yeah, it's done.

**Comment by joan38** [comment]
@alexarchambault tho there is this one:
https://github.com/sbt/sbt/issues/4720
Is there a coursier ticket for this?
