### ISSUE TITLE
Cannot find main class

### ISSUE THREAD

**Issue by 2m** [coursier/coursier#839]
When running:

    coursier launch lt.dvim.sssio:sssio_2.12:0.0.1

I get 

    Cannot find default main class. Specify one with -M or --main.

The [jar](http://central.maven.org/maven2/lt/dvim/sssio/sssio_2.12/0.0.1/sssio_2.12-0.0.1.jar) has the following manifest file:

```
Manifest-Version: 1.0
Implementation-Title: sssio
Implementation-Version: 0.0.1
Specification-Vendor: https://github.com/2m/sssio/graphs/contributors
Specification-Title: sssio
Implementation-Vendor-Id: lt.dvim.sssio
Specification-Version: 0.0.1
Implementation-URL: https://github.com/2m/sssio
Implementation-Vendor: https://github.com/2m/sssio/graphs/contributors
Main-Class: lt.dvim.sssio.Sssio

```

If I add `--main lt.dvim.sssio.Sssio` to the command, then it works.

Tried it with coursier launcher from `1.0.1`, as `1.0.2` and `1.1.0-M1` are broken.

**Comment by alexarchambault** [comment]
Increasing verbosity with `-v -v` , it says
```
Found main classes:
  com.kenai.jffi.Main (vendor: , title: )
  lt.dvim.sssio.Sssio (vendor: https://github.com/2m/sssio/graphs/contributors, title: sssio)
```
The main class detection code is around [here](https://github.com/coursier/coursier/blob/595f7d7d48c0c38bded88531d1fe1cdeb3ccc07c/cli/src/main/scala-2.12/coursier/cli/Helper.scala#L843). It's not been though out much, so I guess it could be tweaked to handle that case…

**Comment by 2m** [comment]
Ahh. I only tried it with one `-v`  :)

**Comment by baroquebobcat** [comment]
I think that it might be that https://github.com/coursier/coursier/blob/595f7d7d48c0c38bded88531d1fe1cdeb3ccc07c/cli/src/main/scala-2.12/coursier/cli/Helper.scala#L46 should use `Implementation-Vendor-Id` instead of `Specification-Vendor`

From the docs, https://docs.oracle.com/javase/7/docs/technotes/guides/extensions/versioning.html, and from some usages I found when googling, it looks like this is more likely to be a maven org-like string.
