### ISSUE TITLE
Stop relying on directory listings

### ISSUE THREAD

**Issue by alexarchambault** [coursier/coursier#896]
[will add details later] These were read to circumvent buggy packaging info in some POMs, but turned out not fully addressing the issue at the end. The initial issue was ultimately fixed by returning "optional" artifacts, that may throw a not found error when attempting to download them (which should be ignored).

**Comment by wisechengyi** [comment]
Interested in the how this affect the result of the resolve.

On a operational perspective, this would be great, because we use a virtual repo which is an aggregate of multiple repos, so doing directory listing is super expensive due to lacking of persistent caching, which can take up to 5 sec per request without cache, and extending the caching period for directory listing would affect the update propagation. On the other hand, hitting an individual file is always cached a lot faster.
